version: '3.9'
services:
  server:
    #docker build -t server:latest .
    image: server:latest
    restart: always
    volumes:
        - ./server:/app
    environment:
      - SERVER_PORT=5000
    ports:
      - 5000:5000
    networks:
      - backplane

  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: DatabasePassword8675309!
    volumes:
      - db-data:/var/lib/mysql
      - ./database/init/:/docker-entrypoint-initdb.d/
    networks:
      - backplane

  proxy:
    image: nginx:alpine
    restart: always
    networks:
      - backplane
    ports:
      - 80:80
      - 443:443
    environment:
      - PROXY_PASS_WEBSITE=172.17.0.1
      - PROXY_PASS_SERVER=172.17.0.1
      #- BACKEND_IP=172.17.0.1
      #- BACKEND_IP=143.198.13.195
      - WEBSITE_NAME=pollpal.io
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      #- ./nginx/debug.conf:/etc/nginx/nginx.conf:ro
      - nginx-logs:/etc/nginx/logs
      - ./nginx/live:/etc/letsencrypt/live
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  nginx-logs:
  db-data:
networks:
  backplane:

