version: '3.9'
services:
    proxy:
        image: nginx
        restart: always
        environment:
            - NGINX_HOST=pollpal.io
            - UPSTREAM_PORT=5000
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - nginx-logs:/var/log/nginx
        command: [nginx-debug, '-g', 'daemon off;']

volumes:
    nginx-logs:
