version: '3.9'
services:
  database:
    image: mysql:latest
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: DatabasePassword8675309!
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
